import Head from 'next/head'
import { Inter } from 'next/font/google'
import localFont from '@next/font/local'
import MediaCard from '../Components/InteractiveContentBlock/MediaCard/index';
import ScrollGifBlock from '@/Components/InteractiveContentBlock/ScrollGifBlock'
import FilteredContentBlock from '@/Components/InteractiveContentBlock/FilteredContentBlock';
import VideoCarousel from '@/Components/VideoCarousel';
import LargeStat from '@/Components/LargeStat';
import SocialValidation from '@/Components/SocialValidation';
import LogoBanner from '@/Components/LogoBanner';
import LogoWall from '@/Components/LogoWall';
import QuickStart from '@/Components/QuickStart';
import Help from '@/Components/Help';
import Filters from '@/Components/Filters';
import StyledHeader from '@/Components/Header';

const inter = Inter({ subsets: ['latin'] })

// const helvatica = localFont({
//   src: '../assets/font/HelveticaNeue-Light.otf',
//   variable: '--helvatica-neue-light'
// })

export default function Home() {
  const centerCardsData = [
    {
      title: "Add Hotspots",
      description: "Short description, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      urlLink: "#",
      urlTitle: "Learn More",
      mediaUrl: "https://thumbs.gfycat.com/MetallicRemarkableLice.webp",
    },
    {
      title: "Add Overlays",
      description: "Short description, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      urlLink: "#",
      urlTitle: "Learn More",
      mediaUrl: "https://prezibase.com/wp-content/uploads/2015/05/the-future-hud-technology-animated-prezi-template.gif",
    },
    {
      title: "Add Shoppable CTAs",
      description: "Short description, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      urlLink: "#",
      urlTitle: "Learn More",
      mediaUrl: "https://i.pinimg.com/originals/74/c8/16/74c81634df9087d04879088aa5c2ee50.gif",
    }
  ];

  const rightCardsData = [
    {
      title: "Add Hotspots",
      description: "Short description, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      urlLink: "#",
      urlTitle: "Learn More",
      mediaUrl: "https://thumbs.gfycat.com/MetallicRemarkableLice.webp",
    },
    {
      title: "Add Overlays",
      description: "Short description, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      urlLink: "#",
      urlTitle: "Learn More",
      mediaUrl: "https://prezibase.com/wp-content/uploads/2015/05/the-future-hud-technology-animated-prezi-template.gif",
    }];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <StyledHeader />
        <MediaCard alignment='down' mediaTitle='Drive engagement & clicks' mediaDesc='Make your customers lean in and take action.' cardsData={centerCardsData} />
        <MediaCard alignment='left' mediaTitle='Collaborate with Ease' mediaDesc='Give and Consolidate Feedback Quickly' cardsData={centerCardsData} />
        <MediaCard alignment="right" mediaTitle="Vimeo Mobile App" mediaDesc="Work from anywhere" mediaSubDesc="Short description, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua." cardsData={rightCardsData} btn1Url="#" btn2Url="#" btn1Title="Download iOS" btn2Title="Download Android" />
        <ScrollGifBlock />
        <FilteredContentBlock />
        <VideoCarousel />
        <LargeStat />
        <SocialValidation />
        <LogoBanner />
        <LogoWall />
        <QuickStart />
        <Help />
        <Filters />
      </main>
    </>
  )
}
